# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9447b508f384fc602a0b4014b4e96a989f6a6cec8398b59e2e4e05819b3ba9afbcf2175e5a4e8ec652493ad93544d9f84dfc273f278cd0f8bde522e16be61f25

test:
  secret_key_base: 9b1153d89e7026da208dc5911a9e9be687498671104375b339e1484c50ee9cc4999668bbf42922f7fb6d84c8eeb81d6aeae8dc7220d43308ffc7cc084ebd629e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
